package:
  name: pubchem-utils
  version: 0.2

build:
  number: 1

source:
  git_url: git@github.com:skearnes/pubchem-utils.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/skearnes/pubchem-utils
  license: BSD
