package:
  name: qchem-utils
  version: 0.1

source:
  git_url: git@github.com:rmcgibbo/qchem-utils.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

about:
  home: https://github.com/rmcgibbo/qchem-utils
  license: GPLv2
