package:
  name: rdkit
  version: 2014.03.1

source:
  fn: Release_2014_03_1.zip
  url: https://github.com/rdkit/rdkit/archive/Release_2014_03_1.zip

build:
  number: 3 

requirements:
  build:
    - cmake [unix]
    - requests
    - boost
    - python
    - numpy
    - pil [py2k]
    - freetype
    - py2cairo [linux and py2k]
  run:
    - boost
    - python
    - numpy

test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
